[package]
name = "tiny_http"
version = "0.1.0"
authors = ["White-Oak <lpzhelud@gmail.com>"]

[dependencies]
tiny_http = "0.5"

[dependencies.multipart]
version = "0.5.1"
default-features = false
features = ["server", "tiny_http"]
